module.exports.getAllProducts = require('./getAllProducts.service')
module.exports.getFeaturedProducts = require('./getFeaturedProduct.service')
module.exports.admingetAllProducts = require('./admingetAllproducts.services')
module.exports.addProduct = require('./addProduct.services')
module.exports.addCategory = require('./addCategory.services')
module.exports.findProductByName = require('./getProductsByName.service')
module.exports.getAllBrandNames = require('./getBrandNames.service')
module.exports.updateProduct = require('./updateProduct.service')
module.exports.getProductById = require('./getProductById.service')
module.exports.updateProductInventory = require('./updateInventory.services')
module.exports.getSerchProducts = require('./getSearchForProducts.services')
module.exports.deleteProduct = require('./deleteProduct.services')
module.exports.featureTOggle = require('./featureTOggle.services')
module.exports.visibleTOggle = require('./visibleTOggle.services')
module.exports.getAllProductsAdmin = require('./getAllProductsAdmin.services')
module.exports.addProductInBrandCatogry = require('./addProductBrandCatogry.services')
module.exports.getProductByName = require('./getProductByName.service')



